function result = diag_point_speed(duration,rollDeg,preset,gain,solver,step,pitchDeg)
%DIAG_POINT_SPEED Measure vertex attitude and all three wheel speeds.
%   diag_point_speed(40,3,"fast",0,"ODE3",0.001)
%   diag_point_speed(60,3,"point_near_zero",7e-5,"ODE5",0.000125)

if nargin<1, duration=40; end
if nargin<2, rollDeg=3; end
if nargin<3, preset="fast"; end
if nargin<4, gain=0; end
if nargin<5, solver="ODE3"; end
if nargin<6, step=0.001; end
if nargin<7, pitchDeg=0; end
setup_cubli();
P = cubli_mode("point_balance",{ ...
    'run.point.duration',duration; ...
    'run.point.initialRollDeg',rollDeg; ...
    'run.point.initialPitchDeg',pitchDeg; ...
    'run.balancePreset',preset; ...
    'run.pointLowSpeed.Kw',gain; ...
    'run.pointNearZero.Kw',gain});
model = build_cubli_clean_cubli('Cubli_PointSpeed_Diag');
set_param(model,'SimMechanicsOpenEditorOnUpdate','off');
set_param([model '/Solver Configuration'], ...
    'MultibodyLocalSolverChoice',char(solver), ...
    'MultibodyLocalSolverSampleTime',num2str(step,16));
assert(strcmp(get_param([model '/Solver Configuration'], ...
    'MultibodyLocalSolverChoice'),char(solver)) && ...
    abs(str2double(get_param([model '/Solver Configuration'], ...
    'MultibodyLocalSolverSampleTime'))-step)<1e-12, ...
    'CubliClean:PointSolverSetting','The contact solver setting did not take.');
assignin('base','P',P);
out = sim(model,'ReturnWorkspaceOutputs','on');

ts = out.get('cubli_com');
t = ts.Time(:).';
com = cubli_log_reshape(ts,3);
wx = localSample(out.get('cubli_wx'),1,t);
wy = localSample(out.get('cubli_wy'),1,t);
wz = localSample(out.get('cubli_wz'),1,t);
rr = localSample(out.get('cubli_R'),9,t);
R = reshape(rr,3,3,[]);
n = [1;1;1]/sqrt(3);
u = squeeze(pagemtimes(R,n));
tilt = atan2(hypot(u(1,:),u(2,:)),u(3,:))*180/pi;
speed = sqrt(wx.^2+wy.^2+wz.^2);
tail = t>=max(0,t(end)-min(10,t(end)/2));
pen = max(out.get('cubli_penetration').Data(:));
result = struct('duration',t(end),'rollDeg',rollDeg,'pitchDeg',pitchDeg, ...
    'preset',string(preset),'gain',gain,'solver',string(solver), ...
    'step',step,'wheelEnd',[wx(end),wy(end),wz(end)], ...
    'wheelNormEnd',speed(end),'wheelNormTailMax',max(speed(tail)), ...
    'wheelNormPeak',max(speed), ...
    'wheelTailMean',[mean(wx(tail)),mean(wy(tail)),mean(wz(tail))], ...
    'tiltEndDeg',tilt(end),'tiltPeakDeg',max(tilt), ...
    'tiltTailMaxDeg',max(abs(tilt(tail))), ...
    'comZEnd',com(3,end),'comZTailMin',min(com(3,tail)), ...
    'comXYEnd',com(1:2,end),'comXYDrift',norm(com(1:2,end)-com(1:2,1)), ...
    'penetrationMax',pen);
clear t com wx wy wz rr R u tilt speed tail
result.report = cubli_run_report(out.get('cubli_com'),out.get('cubli_rate'), ...
    out.get('cubli_tau_x'),out.get('cubli_tau_y'),out.get('cubli_tau_z'), ...
    out.get('cubli_penetration'),P,out.get('cubli_R'),out.get('cubli_wy'), ...
    out.get('cubli_route_state'),out.get('cubli_wx'),out.get('cubli_wz'));
fprintf('%s @ %.4g s, initial [%.2f %.2f] deg, %s Kw %.3g: ', ...
    solver,step,rollDeg,pitchDeg,preset,gain);
fprintf('w end [%.3f %.3f %.3f], |w| tail max %.3f, peak %.1f, ', ...
    result.wheelEnd,result.wheelNormTailMax,result.wheelNormPeak);
fprintf('tilt end %.3f deg, tilt tail max %.3f deg, ', ...
    result.tiltEndDeg,result.tiltTailMaxDeg);
fprintf('z end %.5f, XY drift %.1f mm, pen max %.2f mm\n', ...
    result.comZEnd,1000*result.comXYDrift,1000*result.penetrationMax);
close_system(model,0);
end

function v = localSample(ts,n,t)
v = cubli_log_reshape(ts,n);
if ~isequal(ts.Time(:),t(:))
    v = interp1(ts.Time(:),v.',t(:)).';
end
end
