function model = build_cubli_clean_cubli(modelName)
%BUILD_CUBLI_CLEAN_CUBLI The single free-contact Cubli plant.
%
% One model serves every mode. A free 6-DOF cube rests on a physical Spatial
% Contact Force, all three reaction wheels are motorized, and one controller
% block selects its behaviour from P.run.mode. This is the real plant; the
% ideal-support rigs (G1, G3A/B/C/I) stay as control-law development benches.
%
% Stage A scope: the cube starts at the balance attitude as an initial
% condition and must hold it for 10 s on real contact. It does not claim a
% stand-up, which the rebuild spec permits.
%
% Free body has no joint angle, so the tilt the controller needs cannot come
% from a joint. It is reconstructed from measured quantities instead:
%   theta  = asin(com_x / d),  d = COM-to-edge distance at the balance attitude
%   thetad = omega_y           (world-Y angular rate)
% which is exact for a cube rolling about its contact edge.

root = cubli_root();
setup_cubli();   % 源码分在四个文件夹，全部上路径
P = cubli_clean_parameters();
if nargin < 1 || isempty(modelName), modelName = 'Cubli_Clean_Cubli'; end
model = char(modelName);
target = fullfile(root,[model '.slx']);
if bdIsLoaded(model), close_system(model,0); end
if isfile(target), delete(target); end
new_system(model);
open_system(model);

% --- Plant -------------------------------------------------------------
localAdd(model,'sm_lib/Frames and Transforms/World Frame','World Frame',[35 160 75 200]);
localAdd(model,'sm_lib/Utilities/Mechanism Configuration','Mechanism Configuration',[35 55 115 95]);
localAdd(model,'nesl_utility/Solver Configuration','Solver Configuration',[35 270 115 310]);
localAdd(model,'sm_lib/Frames and Transforms/Rigid Transform','Ground Pose',[150 400 205 440]);
localAdd(model,'sm_lib/Body Elements/Brick Solid','Ground',[270 400 325 440]);
localAdd(model,'sm_lib/Joints/6-DOF Joint','Free Body',[150 135 210 190]);
localAdd(model,'sm_lib/Body Elements/Brick Solid','Cube',[300 135 355 175]);
localAdd(model,'sm_lib/Forces and Torques/Spatial Contact Force','Ground Contact',[430 400 490 440]);

wheelNames = ["Wheel X","Wheel Y","Wheel Z"];
wheelPoses = ["Wheel X Pose","Wheel Y Pose","Wheel Z Pose"];
wheelJoints = ["Wheel X Joint","Wheel Y Joint","Wheel Z Joint"];
rotations = { '[0 0 1; 0 1 0; -1 0 0]', ...
              '[1 0 0; 0 0 -1; 0 1 0]', ...
              '[1 0 0; 0 1 0; 0 0 1]' };
for k = 1:3
    y = 45 + (k-1)*70;
    localAdd(model,'sm_lib/Frames and Transforms/Rigid Transform',char(wheelPoses(k)),[450 y 505 y+40]);
    localAdd(model,'sm_lib/Joints/Revolute Joint',char(wheelJoints(k)),[570 y 625 y+40]);
    localAdd(model,'sm_lib/Body Elements/Cylindrical Solid',[char(wheelNames(k)) ' Rotor'],[690 y 745 y+40]);
end

set_param([model '/Mechanism Configuration'],'GravityVector', ...
    sprintf('[0 0 %.16g]',-P.world.gravity));
set_param([model '/Solver Configuration'],'MultibodyUseLocalSolver','on');
set_param([model '/Solver Configuration'],'MultibodyLocalSolverChoice', ...
    P.sim.localSolver.contact.choice);
set_param([model '/Solver Configuration'],'MultibodyLocalSolverSampleTime', ...
    num2str(P.sim.localSolver.contact.sampleTime));
localTransform(model,'Ground Pose','[0 0 -0.005]','[1 0 0; 0 1 0; 0 0 1]');
for k = 1:3
    localTransform(model,char(wheelPoses(k)), ...
        localVector(P.geometry.wheelCenters(k,:)),rotations{k});
end

localBrick(model,'Ground','[4 4 0.01]','1','[0.32 0.32 0.32]');
set_param([model '/Ground'],'ExportEntireGeometry','on');
localBrick(model,'Cube',sprintf('[%.16g %.16g %.16g]', ...
    P.cube.side,P.cube.side,P.cube.side),num2str(P.cube.mass),'[0.08 0.36 0.82]');
set_param([model '/Cube'],'InertiaType','Custom');
cubeJ = P.cube.mass*P.cube.side^2/6;
set_param([model '/Cube'],'MomentsOfInertia',sprintf('[%.16g %.16g %.16g]',cubeJ,cubeJ,cubeJ));
set_param([model '/Cube'],'ProductsOfInertia','[0 0 0]');
set_param([model '/Cube'],'GraphicOpacity','0.35');
set_param([model '/Cube'],'ExportEntireGeometry','on');
for k = 1:3
    localWheel(model,[char(wheelNames(k)) ' Rotor'],P);
end

% --- Initial condition: balanced on one body edge ----------------------
% R_bal is the attitude whose lowest pair of vertices is the contact edge:
% the body z axis lies along world -Y (the edge) and the body (1,1,0)
% diagonal points up, so the COM sits directly above the edge at d = side/sqrt2.
% Verified against G1's ideal rig, whose Edge Axis * Cube Pose composition is
% exactly this matrix.
% These are written as workspace EXPRESSIONS, not literals: the model reads
% P.run.* from the base workspace when it compiles, so switching P.run.mode
% and re-running changes behaviour without regenerating this .slx.
edgeD = P.geometry.edgeHeight;
set_param([model '/Free Body'],'PzPositionTargetSpecify','on');
set_param([model '/Free Body'],'PzPositionTargetValue','P.run.ic.z');
set_param([model '/Free Body'],'PxPositionTargetSpecify','on');
set_param([model '/Free Body'],'PxPositionTargetValue','P.run.ic.x');
set_param([model '/Free Body'],'PyPositionTargetSpecify','on');
set_param([model '/Free Body'],'PyPositionTargetValue','P.run.ic.y');
set_param([model '/Free Body'],'SphPositionTargetSpecify','on');
set_param([model '/Free Body'],'SphPositionTargetRotationMethod','RotationMatrix');
set_param([model '/Free Body'],'SphPositionTargetRotationMatrix','P.run.ic.R');
% Velocities are left at their default of zero: the cube is placed at the
% tilted attitude at rest, so the whole motion comes from the instability.

% Workspace expressions, not literals, so a capability can select its own
% contact law without regenerating the model. The vertex mode needs this: the
% SmoothStickSlip friction model runs a stick-slip limit cycle at a SINGLE
% point contact and injects ~0.074 rad/s of spurious rate within 50 ms, where
% the instability only accounts for ~1e-9. Turning friction off there drops it
% to 4.9e-15 (measured).
set_param([model '/Ground Contact'],'NormalStiffness','P.contact.normalStiffness');
set_param([model '/Ground Contact'],'NormalDamping','P.contact.normalDamping');
set_param([model '/Ground Contact'],'CoefficientOfStaticFriction','P.contact.staticFriction');
set_param([model '/Ground Contact'],'CoefficientOfDynamicFriction','P.contact.kineticFriction');
% FrictionType is an ENUM, so it cannot be a workspace expression; a capability
% disables friction by zeroing the two coefficients instead.
set_param([model '/Ground Contact'],'FrictionType','SmoothStickSlip');
set_param([model '/Ground Contact'],'SensePenetrationDepth','on');
for k = 1:3
    set_param([model '/' char(wheelJoints(k))],'TorqueActuationMode','InputTorque');
    set_param([model '/' char(wheelJoints(k))],'SenseVelocity','on');
end

% --- Measurement -------------------------------------------------------
localAdd(model,'sm_lib/Frames and Transforms/Transform Sensor','Cube COM Sensor',[520 520 575 560]);
localAdd(model,'sm_lib/Frames and Transforms/Transform Sensor','Cube Rate Sensor',[520 580 575 620]);
localAdd(model,'sm_lib/Frames and Transforms/Transform Sensor','Cube Attitude Sensor',[520 640 575 680]);
localAdd(model,'nesl_utility/PS-Simulink Converter','Cube COM XYZ',[650 520 710 550]);
localAdd(model,'nesl_utility/PS-Simulink Converter','Cube Rate XYZ',[650 580 710 610]);
localAdd(model,'nesl_utility/PS-Simulink Converter','Cube Attitude R',[650 640 710 670]);
localAdd(model,'nesl_utility/PS-Simulink Converter','Contact Penetration',[650 700 710 730]);
set_param([model '/Cube COM Sensor'],'SenseXYZ','on');
set_param([model '/Cube Rate Sensor'],'SenseOmega','on');
% Attitude is not optional. With friction OFF (the vertex mode) there is no
% horizontal force on the cube, so its horizontal momentum is conserved and the
% COM CANNOT translate sideways: measured, com_x and com_y hold their initial
% values bit-for-bit for 10 s while com_z falls 0.13 -> 0.075. A tilt read from
% com_x is therefore a CONSTANT, and a control law built on it has no position
% feedback at all -- only the rate term is live. That is why raising Kp had no
% effect at the vertex. The tilt has to come from the attitude, which is exact
% and does not care whether the contact slides.
set_param([model '/Cube Attitude Sensor'],'SenseR','on');
% World components: a body-frame rate is useless for a world-axis pendulum.
set_param([model '/Cube Rate Sensor'],'MeasurementFrame','World');
set_param([model '/Cube COM XYZ'],'Unit','m');
set_param([model '/Cube Rate XYZ'],'Unit','rad/s');
set_param([model '/Contact Penetration'],'Unit','m');

wheelSpeedNames = strings(1,3);
for k = 1:3
    wheelSpeedNames(k) = sprintf('Wheel %s Speed',extractAfter(wheelNames(k),"Wheel "));
    localAdd(model,'nesl_utility/PS-Simulink Converter',char(wheelSpeedNames(k)), ...
        [650 700+(k-1)*50 710 730+(k-1)*50]);
    set_param([model '/' char(wheelSpeedNames(k))],'Unit','rad/s');
end
localAdd(model,'simulink/Signal Routing/Mux','Wheel Speeds',[770 700 775 800]);
set_param([model '/Wheel Speeds'],'Inputs','3');

% --- Controller --------------------------------------------------------
localAdd(model,'simulink/Sources/Constant','Run Mode',[520 460 570 490]);
set_param([model '/Run Mode'],'Value','P.run.modeCode','OutDataTypeStr','double');
% Gains and manoeuvre constants arrive as a workspace expression, so they can
% be changed and re-run without regenerating the model.
localAdd(model,'simulink/Sources/Constant','Controller Params',[520 400 600 430]);
set_param([model '/Controller Params'],'Value','P.run.ctrl','OutDataTypeStr','double');
localAdd(model,'simulink/Sources/Constant','Route Params',[520 285 600 315]);
set_param([model '/Route Params'],'Value','P.run.route.ctrl','OutDataTypeStr','double');
localAdd(model,'simulink/Sources/Constant','Point Speed Params',[520 245 600 275]);
set_param([model '/Point Speed Params'],'Value','P.run.pointSpeed.ctrl', ...
    'OutDataTypeStr','double');
% The controller integrates the wheel-speed bias, so it needs time. A Clock is
% used rather than a fixed dt because the block runs at the solver's variable
% step, not at a fixed rate.
localAdd(model,'simulink/Sources/Clock','Controller Clock',[520 340 570 370]);
localAdd(model,'simulink/User-Defined Functions/MATLAB Function','Cubli Controller',[860 470 1010 560]);
localAdd(model,'simulink/Signal Routing/Demux','Torque Demux',[1050 470 1055 540]);
set_param([model '/Torque Demux'],'Outputs','3');
localAdd(model,'simulink/Discrete/Unit Delay','Torque X Hold',[1090 440 1145 470]);
localAdd(model,'simulink/Discrete/Unit Delay','Torque Y Hold',[1090 490 1145 520]);
localAdd(model,'simulink/Discrete/Unit Delay','Torque Z Hold',[1090 540 1145 570]);
for nm = ["Torque X Hold" "Torque Y Hold" "Torque Z Hold"]
    set_param([model '/' char(nm)],'SampleTime',num2str(P.sim.controlPeriod), ...
        'InitialCondition','0');
end
localAdd(model,'nesl_utility/Simulink-PS Converter','Torque X',[1190 440 1250 470]);
localAdd(model,'nesl_utility/Simulink-PS Converter','Torque Y',[1190 490 1250 520]);
localAdd(model,'nesl_utility/Simulink-PS Converter','Torque Z',[1190 540 1250 570]);
for nm = ["Torque X" "Torque Y" "Torque Z"]
    set_param([model '/' char(nm)],'Unit','N*m');
end

% --- Logs --------------------------------------------------------------
localLog(model,'Log Cube COM','cubli_com',[800 520 920 550]);
localLog(model,'Log Cube Rate','cubli_rate',[800 580 920 610]);
localLog(model,'Log Cube Attitude','cubli_R',[800 640 920 670]);
localLog(model,'Log Penetration','cubli_penetration',[800 700 920 730]);
% Wheel speeds are logged individually as well as multiplexed into the
% controller: without them a torque that never reaches the rotor looks
% identical to a controller sign error.
for k = 1:3
    localLog(model,sprintf('Log Wheel %s Speed',extractAfter(wheelNames(k),"Wheel ")), ...
        sprintf('cubli_w%s',lower(extractAfter(wheelNames(k),"Wheel "))), ...
        [1300 620+(k-1)*50 1420 650+(k-1)*50]);
end
localLog(model,'Log Torque X','cubli_tau_x',[1300 440 1420 470]);
localLog(model,'Log Torque Y','cubli_tau_y',[1300 490 1420 520]);
localLog(model,'Log Torque Z','cubli_tau_z',[1300 540 1420 570]);
localLog(model,'Log Route State','cubli_route_state',[1300 820 1420 850]);
localSetController(model);

% --- Physical network --------------------------------------------------
add_line(model,'World Frame/RConn1','Mechanism Configuration/RConn1','autorouting','on');
add_line(model,'World Frame/RConn1','Solver Configuration/RConn1','autorouting','on');
add_line(model,'World Frame/RConn1','Ground Pose/LConn1','autorouting','on');
add_line(model,'Ground Pose/RConn1','Ground/RConn1','autorouting','on');
add_line(model,'World Frame/RConn1','Free Body/LConn1','autorouting','on');
add_line(model,'Free Body/RConn1','Cube/RConn1','autorouting','on');
for k = 1:3
    add_line(model,'Cube/RConn1',[char(wheelPoses(k)) '/LConn1'],'autorouting','on');
    add_line(model,[char(wheelPoses(k)) '/RConn1'],[char(wheelJoints(k)) '/LConn1'],'autorouting','on');
    add_line(model,[char(wheelJoints(k)) '/RConn1'],[char(wheelNames(k)) ' Rotor/RConn1'],'autorouting','on');
end
add_line(model,'Ground/LConn1','Ground Contact/LConn1','autorouting','on');
add_line(model,'Ground Contact/RConn1','Cube/LConn1','autorouting','on');

% --- Signal network ----------------------------------------------------
add_line(model,'World Frame/RConn1','Cube COM Sensor/LConn1','autorouting','on');
add_line(model,'Cube/RConn1','Cube COM Sensor/RConn1','autorouting','on');
add_line(model,'World Frame/RConn1','Cube Rate Sensor/LConn1','autorouting','on');
add_line(model,'Cube/RConn1','Cube Rate Sensor/RConn1','autorouting','on');
add_line(model,'World Frame/RConn1','Cube Attitude Sensor/LConn1','autorouting','on');
add_line(model,'Cube/RConn1','Cube Attitude Sensor/RConn1','autorouting','on');
add_line(model,'Cube COM Sensor/RConn2','Cube COM XYZ/LConn1','autorouting','on');
add_line(model,'Cube Rate Sensor/RConn2','Cube Rate XYZ/LConn1','autorouting','on');
add_line(model,'Cube Attitude Sensor/RConn2','Cube Attitude R/LConn1','autorouting','on');
localConnectSenses(model,'Ground Contact','Contact Penetration');
for k = 1:3
    add_line(model,[char(wheelJoints(k)) '/RConn2'],[char(wheelSpeedNames(k)) '/LConn1'],'autorouting','on');
    add_line(model,[char(wheelSpeedNames(k)) '/1'],sprintf('Wheel Speeds/%d',k),'autorouting','on');
    add_line(model,[char(wheelSpeedNames(k)) '/1'], ...
        sprintf('Log Wheel %s Speed/1',extractAfter(wheelNames(k),"Wheel ")),'autorouting','on');
end
add_line(model,'Run Mode/1','Cubli Controller/1','autorouting','on');
add_line(model,'Cube COM XYZ/1','Cubli Controller/2','autorouting','on');
add_line(model,'Cube Rate XYZ/1','Cubli Controller/3','autorouting','on');
add_line(model,'Cube Attitude R/1','Cubli Controller/4','autorouting','on');
add_line(model,'Wheel Speeds/1','Cubli Controller/5','autorouting','on');
add_line(model,'Controller Params/1','Cubli Controller/6','autorouting','on');
add_line(model,'Controller Clock/1','Cubli Controller/7','autorouting','on');
add_line(model,'Route Params/1','Cubli Controller/8','autorouting','on');
add_line(model,'Point Speed Params/1','Cubli Controller/9','autorouting','on');
add_line(model,'Cubli Controller/1','Torque Demux/1','autorouting','on');
add_line(model,'Cubli Controller/2','Log Route State/1','autorouting','on');
add_line(model,'Torque Demux/1','Torque X Hold/1','autorouting','on');
add_line(model,'Torque Demux/2','Torque Y Hold/1','autorouting','on');
add_line(model,'Torque Demux/3','Torque Z Hold/1','autorouting','on');
add_line(model,'Torque X Hold/1','Torque X/1','autorouting','on');
add_line(model,'Torque Y Hold/1','Torque Y/1','autorouting','on');
add_line(model,'Torque Z Hold/1','Torque Z/1','autorouting','on');
add_line(model,'Torque X/RConn1','Wheel X Joint/LConn2','autorouting','on');
add_line(model,'Torque Y/RConn1','Wheel Y Joint/LConn2','autorouting','on');
add_line(model,'Torque Z/RConn1','Wheel Z Joint/LConn2','autorouting','on');
add_line(model,'Cube COM XYZ/1','Log Cube COM/1','autorouting','on');
add_line(model,'Cube Rate XYZ/1','Log Cube Rate/1','autorouting','on');
add_line(model,'Cube Attitude R/1','Log Cube Attitude/1','autorouting','on');
add_line(model,'Contact Penetration/1','Log Penetration/1','autorouting','on');
add_line(model,'Torque X Hold/1','Log Torque X/1','autorouting','on');
add_line(model,'Torque Y Hold/1','Log Torque Y/1','autorouting','on');
add_line(model,'Torque Z Hold/1','Log Torque Z/1','autorouting','on');

set_param(model,'StopTime','P.run.duration','Solver','ode23t', ...
    'MaxStep','0.001','RelTol','1e-4');
save_system(model,target);
open_system(model);
fprintf(['Created %s\nUnified Cubli plant: mode "%s" (code %d), %.1f s. ' ...
    'Free contact, 3 motorized wheels.\n'],target,P.run.mode,P.run.modeCode,P.run.edge.duration);
end

function localAdd(model,source,name,position)
add_block(source,[model '/' name],'Position',position);
end

function localConnectSenses(model,block,varargin)
ph = get_param([model '/' block],'PortHandles');
nR = numel(ph.RConn);
assert(nR == 1 + numel(varargin),'CubliClean:UnexpectedSensorPorts', ...
    '%s exposes %d RConn ports, expected %d.',block,nR,1+numel(varargin));
for k = 1:numel(varargin)
    add_line(model,sprintf('%s/RConn%d',block,k+1),[varargin{k} '/LConn1'],'autorouting','on');
end
end

function localLog(model,block,varName,position)
localAdd(model,'simulink/Sinks/To Workspace',block,position);
set_param([model '/' block],'VariableName',varName,'SaveFormat','Timeseries');
end

function localTransform(model,name,translation,rotation)
path = [model '/' name];
set_param(path,'TranslationMethod','Cartesian');
set_param(path,'TranslationCartesianOffset',translation);
set_param(path,'RotationMethod','RotationMatrix');
set_param(path,'RotationMatrix',rotation);
end

function localBrick(model,name,dimensions,mass,color)
path = [model '/' name];
set_param(path,'BrickDimensions',dimensions);
set_param(path,'Mass',mass);
set_param(path,'CenterOfMass','[0 0 0]');
set_param(path,'GraphicDiffuseColor',color);
end

function localWheel(model,name,P)
path = [model '/' name];
set_param(path,'InertiaType','CalculateFromGeometry');
set_param(path,'CylinderRadius',num2str(P.wheel.radius));
set_param(path,'CylinderLength',num2str(P.wheel.thickness));
set_param(path,'Density',num2str(P.wheel.mass/(pi*P.wheel.radius^2*P.wheel.thickness)));
set_param(path,'GraphicDiffuseColor','[0.95 0.45 0.06]');
end

function localSetController(model)
rt = sfroot;
charts = rt.find('-isa','Stateflow.EMChart');
idx = find(string({charts.Path}) == string(model) + "/Cubli Controller",1);
assert(~isempty(idx),'CubliClean:CubliController','Could not create Cubli Controller.');
charts(idx).Script = sprintf([ ...
    'function [tau,routeState] = cubli_controller(mode,com,omega,R,w,prm,clk,rprm,pprm)\n' ...
    '%%#codegen\n' ...
    '%% Mode codes match P.run.modes. All gains and manoeuvre constants arrive\n' ...
    '%% in prm, which is the workspace expression P.run.ctrl, so nothing here\n' ...
    '%% is baked and changing a gain does not need a rebuild.\n' ...
    '%%\n' ...
    '%% EDGE modes (1, 2): free body has no joint angle, so the pivot state is\n' ...
    '%% reconstructed from measured scalars. theta is measured about the contact\n' ...
    '%% edge at x=0 and is -45 deg when the cube lies flat with its front edge\n' ...
    '%% there, 0 at the balance attitude. thetad is the world-Y rate. This is\n' ...
    '%% valid because the edge contact has friction, so com_x does track the\n' ...
    '%% tilt. The tipping axis is world Y, and the only wheel whose axis lies\n' ...
    '%% along world Y in BOTH the flat and the edge attitude is Wheel Y, so that\n' ...
    '%% is the actuated one (tau(2) / w(2), not tau(3) / w(3)).\n' ...
    '%%\n' ...
    '%% POINT mode (3): com_x CANNOT be used. The vertex contact runs with\n' ...
    '%% friction off, so no horizontal force acts on the cube, horizontal\n' ...
    '%% momentum is conserved, and com_x/com_y hold their initial values exactly\n' ...
    '%% for the whole run while the cube topples (measured: bit-identical over\n' ...
    '%% 10001 samples as com_z fell 0.1295 -> 0.0747). asin(com_x/h) is therefore\n' ...
    '%% a constant and carries no state. The tilt comes from the attitude: the\n' ...
    '%% body diagonal n=(1,1,1)/sqrt(3) points up at balance, so its world\n' ...
    '%% direction u = Rm*n has u = (theta_y, -theta_x, 1) for small tilts.\n' ...
    'd=prm(1); Kp=prm(2); Kd=prm(3); Kw=prm(4); s=prm(5);\n' ...
    'limit=prm(6); peak=prm(7); wmax=prm(8);\n' ...
    'spinT=prm(9); spinW=prm(10); brakeT=prm(11); capDeg=prm(12);\n' ...
    'boostSec=prm(13);\n' ...
    'KpP=prm(14); KdP=prm(15); KyawP=prm(16); lamP=prm(17); spP=prm(18);\n' ...
    'A=reshape(prm(19:27),3,3);\n' ...
    'pT0=prm(28); pSpinW=prm(29); pT1=prm(30);\n' ...
    'eT0=prm(31); eSpinW=prm(32); eT1=prm(33);\n' ...
    'capTilt=prm(34); capRate=prm(35);\n' ...
    'wDrive=prm(45); wBleed=prm(46); wLand=prm(47); wNstep=prm(48);\n' ...
    'wWheel=prm(49); wSign=prm(50);\n' ...
    'KiE=prm(51); KiP=prm(52); tiltSrc=prm(53); lamW=prm(54);\n' ...
    'dzE=prm(55); KiT=prm(56); KyawE=prm(57); yawRef=prm(58);\n' ...
    'persistent phase tHand jph jw0 jtHand\n' ...
    'if isempty(phase), phase=0; end\n' ...
    'if isempty(tHand), tHand=0; end\n' ...
    '%% walking state. It must be an ACCUMULATED rotation plus a per-step target:\n' ...
    '%% a rotation matrix folds every 360 deg, so an attitude angle cannot say\n' ...
    '%% which face the cube is on after four of them.\n' ...
    'persistent wg wtprev wph wtgt wnDone\n' ...
    'if isempty(wg), wg=0; end\n' ...
    'if isempty(wtprev), wtprev=0; end\n' ...
    'if isempty(wph), wph=0; end\n' ...
    'if isempty(wtgt), wtgt=0; end\n' ...
    'if isempty(wnDone), wnDone=0; end\n' ...
    '%% Route state is independent of the legacy fixed-direction gait.\n' ...
    'persistent rs rp ra rt rw rg rstart rflat rcom0 rax rtravel rdown0 rfault\n' ...
    'if isempty(rs), rs=1; end\n' ...
    'if isempty(rp), rp=0; end\n' ...
    'if isempty(ra), ra=0; end\n' ...
    'if isempty(rt), rt=0; end\n' ...
    'if isempty(rw), rw=1; end\n' ...
    'if isempty(rg), rg=1; end\n' ...
    'if isempty(rstart), rstart=0; end\n' ...
    'if isempty(rflat), rflat=-1; end\n' ...
    'if isempty(rcom0), rcom0=[0;0;0]; end\n' ...
    'if isempty(rax), rax=[0;1;0]; end\n' ...
    'if isempty(rtravel), rtravel=[1;0;0]; end\n' ...
    'if isempty(rdown0), rdown0=[0;0;1]; end\n' ...
    'if isempty(rfault), rfault=0; end\n' ...
    'routeState=[0;0;0];\n' ...
    '%% Rotor-speed integral, the only term that can drive the rotor to zero.\n' ...
    '%% A proportional law cannot: the rotor speed only changes while the\n' ...
    '%% commanded torque is non-zero (wdot = -tau/I_w), and a proportional law\n' ...
    '%% drives its own torque to zero at every point of the balance manifold.\n' ...
    '%% So the rotor FREEZES wherever the entry transient left it, which is\n' ...
    '%% what a 30 s edge run measures (constant 1092 rad/s, true tilt 0.04 deg,\n' ...
    '%% commanded torque oscillating about 0). Dumping that momentum needs an\n' ...
    '%% EXTERNAL torque and the only one is gravity acting on a lean, so the\n' ...
    '%% cube must lean, hand the momentum over, and straighten. An integral of\n' ...
    '%% the rotor speed changes the equilibrium itself -- it makes w = 0 the\n' ...
    '%% only fixed point -- which is why it is an integral and not another gain.\n' ...
    '%%\n' ...
    '%% Accumulated with the same clock difference and the same 20 ms clamp the\n' ...
    '%% walk branch uses. The earlier integral attempt was blamed on the\n' ...
    '%% variable-step chart making the effective gain step-dependent; that is\n' ...
    '%% checked directly in exp_wzero by re-running at a different solver step.\n' ...
    'persistent wsc wtick\n' ...
    'if isempty(wsc), wsc=[0;0;0]; end\n' ...
    'if isempty(wtick), wtick=0; end\n' ...
    'dtw=clk-wtick;\n' ...
    'if dtw>0.02, dtw=0.02; end\n' ...
    'if dtw<0, dtw=0; end\n' ...
    'wtick=clk;\n' ...
    '%% LEAKY integral. A pure integral dumps the rotor but has no reason to\n' ...
    '%% give back what it accumulated, so it ends up holding a standing lean;\n' ...
    '%% gravity then runs away with that lean. Measured over 60 s with a pure\n' ...
    '%% integral: the rotor did hold at +-35 rad/s as intended, but the tilt\n' ...
    '%% drifted monotonically 0 -> -5.9 deg and com_x 0 -> 101 mm (two thirds\n' ...
    '%% of the cube side) -- not an equilibrium, just a slower fall. A 30 s run\n' ...
    '%% could not tell the difference, which is why the long run exists.\n' ...
    '%% The leak makes sigma decay whenever w is small, so the ONLY fixed point\n' ...
    '%% is (w = 0, sigma = 0) and the lean the dump needs becomes transient.\n' ...
    '%% lamW = 0 reproduces the pure integral, for comparison.\n' ...
    'wsc=wsc+(w-lamW*wsc)*dtw;\n' ...
    '%% Edge tilt, in whichever form the law is asked for. "com" is what\n' ...
    '%% shipped: asin(com_x/d). Measured on the free contact, that quantity is\n' ...
    '%% mostly SLIDE -- 5.3 mm of com_x read as 2.86 deg of tilt while R showed\n' ...
    '%% the true attitude level to 0.04 deg. "attitude" reads the rotation\n' ...
    '%% about the contact edge off the body z axis; at the flat attitude it is\n' ...
    '%% exactly -45 deg, the same as the com form, so the flat->edge stand-up\n' ...
    '%% needs no special case.\n' ...
    'if tiltSrc==1\n' ...
    '  Rme=reshape(R,3,3);\n' ...
    '  thE=atan2(Rme(1,3),Rme(3,3))-pi/4;\n' ...
    'else\n' ...
    '  thE=asin(max(-1,min(1,com(1)/d)));\n' ...
    'end\n' ...
    '%% Tilt integral, the cure for the rotor PUMP. Measured: the rotor climbs\n' ...
    '%% 156 -> 1063 rad/s over 55 s, which by w = -(1/I_w)*integral(tau) is a\n' ...
    '%% mean DC torque of just 1.65 mN*m -- an equivalent COM offset of ~0.23 mm\n' ...
    '%% that the law cancels continuously. Integrated, that DC torque becomes\n' ...
    '%% rotor momentum, so the climb IS the bias being paid for.\n' ...
    '%%\n' ...
    '%% A torque DEADBAND does not fix it and was measured not to (exp_deadband,\n' ...
    '%% 120 s): dz = 0, 0.002, 0.005, 0.01 all end at 959-999 rad/s. The pump is\n' ...
    '%% not a SMALL torque, it is a torque whose TIME AVERAGE is non-zero; the\n' ...
    '%% torque swings large both ways and a magnitude filter lets the swing\n' ...
    '%% through with the same net. Removing a time average needs an integrator,\n' ...
    '%% which is the textbook reason PI is used, and its equilibrium here is\n' ...
    '%% tau = 0 at theta = 0 -- so the DC term vanishes and nothing drives w.\n' ...
    '%%\n' ...
    '%% NOTE this integrates the TILT, not the rotor speed. The rotor-speed\n' ...
    '%% integral (KiE, the "wheel_stop" preset) is a different thing and is the\n' ...
    '%% one that winds up and tips the cube over; it is not this.\n' ...
    'persistent ths\n' ...
    'if isempty(ths), ths=0; end\n' ...
    'ths=ths+thE*dtw;\n' ...
    '%% A store speed of zero means no impulse: go straight to the balance law.\n' ...
    '%% Driving u to (0,0,1) IS the climb, so the law is itself a valid\n' ...
    '%% climb controller and the spin-up/brake staging may be unnecessary.\n' ...
    'if isempty(jph)\n' ...
    '  if eSpinW<=0, jph=3; else, jph=0; end\n' ...
    'end\n' ...
    'if isempty(jw0), jw0=0; end\n' ...
    'if isempty(jtHand), jtHand=0; end\n' ...
    'tau=[0;0;0]; tq=0; lim=limit;\n' ...
    '%% Unloading is proportional on the rotor speed. A proportional term can\n' ...
    '%% only move WHERE the rotor freezes, never drive it to zero -- see the\n' ...
    '%% accuracy note on KiE/KiP and the rotor-integral block near the top.\n' ...
    'if mode==1\n' ...
    '  th=thE;\n' ...
    '  tq=s*(Kp*th+Kd*omega(2))+Kw*w(2)+KiE*wsc(2)+KiT*ths;\n' ...
    '  %% TORQUE DEADBAND, aimed at the rotor PUMP. Measured on the shipped\n' ...
    '  %% config: the cube is balanced by 3-5 s with the rotor at only ~150\n' ...
    '  %% rad/s, and the climb to 1092 happens over the next 20 s. The climb is\n' ...
    '  %% a DC torque being integrated into rotor momentum: at t=5..10 s the law\n' ...
    '  %% commands a near-cancellation (-Kp*theta_com + Kw*w ~ 0.005-0.007 N*m)\n' ...
    '  %% whose small residual gives +48..69 rad/s^2. theta_com comes from the\n' ...
    '  %% com_x SLIDE (the true attitude tilt is ~0), so the loop reads a fake\n' ...
    '  %% tilt and answers with a DC torque. Removing the slide from the reading\n' ...
    '  %% (attitude tilt) does NOT work -- three attitude variants all fall over,\n' ...
    '  %% because this com loop is the only thing holding the cube up. So the fix\n' ...
    '  %% has to be on the OUTPUT instead: do not apply a torque too small to be\n' ...
    '  %% a real correction, and the residual has nothing to integrate.\n' ...
    '  %%\n' ...
    '  %% Cost: the loop cannot command below dzE, so the tilt limit-cycles\n' ...
    '  %% within about +-dzE/Kp (dzE=0.01 gives ~0.26 deg, against a 5 deg gate).\n' ...
    '  %% dzE=0 reproduces the shipped behaviour exactly.\n' ...
    '  if abs(tq)<dzE, tq=0; end\n' ...
    'elseif mode==2\n' ...
    '  th=thE;\n' ...
    '  %% Phase 0 stores wheel momentum, 1 spends it, 2 hands over to balance.\n' ...
    '  %% The pulse ends when the rotor has given back everything it stored\n' ...
    '  %% (w crosses zero), NOT when it reaches a speed: braking past zero\n' ...
    '  %% keeps adding impulse and sails the cube over the top.\n' ...
    '  if phase==0 && abs(w(2))>=spinW, phase=1; end\n' ...
    '  if phase==1 && (th>=capDeg*pi/180 || w(2)>=0), phase=2; tHand=clk; end\n' ...
    '  if phase==0\n' ...
    '    tq=spinT; lim=peak;\n' ...
    '  elseif phase==1\n' ...
    '    tq=brakeT; lim=peak;\n' ...
    '  else\n' ...
    '    tq=s*(Kp*th+Kd*omega(2))+Kw*w(2)+KiE*wsc(2)+KiT*ths;\n' ...
    '    if abs(tq)<dzE, tq=0; end\n' ...
    '    %% Peak authority briefly after the handover, so an overshoot can be\n' ...
    '    %% caught; then back to the continuous limit.\n' ...
    '    if clk-tHand<boostSec, lim=peak; end\n' ...
    '  end\n' ...
    'elseif mode==4\n' ...
    '  %% WALK: discrete face-by-face gait. Drive forward until the cube has\n' ...
    '  %% turned one face, stop driving, bleed the rotor back to zero, then\n' ...
    '  %% advance the target by one face. A POSITIVE tau_y drives the cube\n' ...
    '  %% forward (measured with +0.70: com_x -0.075 -> +0.065, body x axis\n' ...
    '  %% ending along world -z, i.e. +90 deg about world Y).\n' ...
    '  %%\n' ...
    '  %% There is deliberately NO store phase here. Stage B stores at -0.40 and\n' ...
    '  %% then reverses with +0.80; applied per step the rotor spends the whole\n' ...
    '  %% reversal being pulled back through zero while the cube is still being\n' ...
    '  %% driven, and it rolls 4-5 faces (measured at spinW 700 and 1300).\n' ...
    '  dtc=clk-wtprev;\n' ...
    '  if dtc>0.02, dtc=0.02; end\n' ...
    '  if dtc<0, dtc=0; end\n' ...
    '  wtprev=clk;\n' ...
    '  %% accumulate the rotation about the axis this direction uses: wheel 2\n' ...
    '  %% turns the cube about world Y (travel along x), wheel 1 about world X\n' ...
    '  %% (travel along y). Accumulating must be a running total: a rotation\n' ...
    '  %% matrix folds every 360 deg and cannot count faces.\n' ...
    '  if wWheel==1\n' ...
    '    wrate=omega(1);\n' ...
    '    wrot=w(1);\n' ...
    '  else\n' ...
    '    wrate=omega(2);\n' ...
    '    wrot=w(2);\n' ...
    '  end\n' ...
    '  wg=wg+wrate*dtc;\n' ...
    '  if wph==0 && abs(wg) >= (wtgt+wLand)*pi/180, wph=1; end\n' ...
    '  if wph==1 && abs(wrot)<50, wph=2; end\n' ...
    '  if wph==2 && wnDone<wNstep\n' ...
    '    wtgt=wtgt+90; wnDone=wnDone+1; wph=0;\n' ...
    '  end\n' ...
    '  if wph==0\n' ...
    '    wtq=wSign*wDrive;\n' ...
    '  elseif wph==1\n' ...
    '    %% bleed on the new face; under the 0.5445 N*m flat-face restoring\n' ...
    '    %% couple this only rocks the cube\n' ...
    '    wtq=-wSign*wBleed;\n' ...
    '  else\n' ...
    '    wtq=0;\n' ...
    '  end\n' ...
    '  if wWheel==1\n' ...
    '    tau=[wtq; 0; 0];\n' ...
    '  else\n' ...
    '    tau=[0; wtq; 0];\n' ...
    '  end\n' ...
    '  tau=min(max(tau,-peak),peak);\n' ...
    '  for i=1:3\n' ...
    '    if abs(w(i))>=wmax && tau(i)*w(i)>0, tau(i)=0; end\n' ...
    '  end\n' ...
    '  return\n' ...
    'elseif mode==9\n' ...
    '  %% Route commands are fixed WORLD directions, codes R=1,L=2,U=3,D=4.\n' ...
    '  %% Positive wheel commands react on the body about [-X,+Y,-Z].\n' ...
    '  %% Select the wheel most aligned with the desired WORLD roll axis.\n' ...
    '  %% Completion also uses the actual down face and displacement, since\n' ...
    '  %% yaw can make the world-axis projection smaller than 90 deg.\n' ...
    '  dtc=clk-rt;\n' ...
    '  if dtc>0.02, dtc=0.02; end\n' ...
    '  if dtc<0, dtc=0; end\n' ...
    '  rt=clk;\n' ...
    '  Rme=reshape(R,3,3);\n' ...
    '  nroute=rprm(1);\n' ...
    '  if rs>nroute, rp=4; end\n' ...
    '  if rp==0\n' ...
    '    code=rprm(1+rs);\n' ...
    '    if code==1, rax=[0;1;0]; rtravel=[1;0;0]; end\n' ...
    '    if code==2, rax=[0;-1;0]; rtravel=[-1;0;0]; end\n' ...
    '    if code==3, rax=[-1;0;0]; rtravel=[0;1;0]; end\n' ...
    '    if code==4, rax=[1;0;0]; rtravel=[0;-1;0]; end\n' ...
    '    best=0;\n' ...
    '    for j=1:3\n' ...
    '      if j==1, axis=-Rme(:,1);\n' ...
    '      elseif j==2, axis=Rme(:,2);\n' ...
    '      else, axis=-Rme(:,3); end\n' ...
    '      align=axis.''*rax;\n' ...
    '      if abs(align)>best, best=abs(align); rw=j; rg=sign(align); end\n' ...
    '    end\n' ...
    '    if best<0.70\n' ...
    '      rp=5; rfault=1;\n' ...
    '    else\n' ...
    '      ra=0; rstart=clk; rcom0=com; rflat=-1;\n' ...
    '      rdown0=Rme(3,:).''; rp=1;\n' ...
    '    end\n' ...
    '  end\n' ...
    '  if rp>=1 && rp<=3\n' ...
    '    ra=ra+(omega.''*rax)*dtc;\n' ...
    '    %% A mixed-axis roll can physically finish one face while its WORLD\n' ...
    '    %% axis projection is only ~72-83 deg. Do not drive forever at the wheel\n' ...
    '    %% speed guard waiting for an impossible 88-deg projection. Require\n' ...
    '    %% a new down face AND most of one side of travel for this fallback.\n' ...
    '    flatNow=max(abs(Rme(3,:)))>=cos(rprm(67)*pi/180);\n' ...
    '    newFace=abs(rdown0.''*Rme(3,:).'')<sin(rprm(67)*pi/180);\n' ...
    '    fullTravel=(com-rcom0).''*rtravel>=0.7*rprm(70);\n' ...
    '    landedFace=ra>=max(55,wLand-25)*pi/180 && flatNow && newFace && fullTravel;\n' ...
    '    if rp==1 && (ra>=wLand*pi/180 || landedFace), rp=2; end\n' ...
    '    if rp==2 && abs(w(rw))<50, rp=3; end\n' ...
    '    if rp==3\n' ...
    '      flat=max(abs(Rme(3,:)))>=cos(rprm(67)*pi/180);\n' ...
    '      slow=sqrt(omega.''*omega)<=rprm(68);\n' ...
    '      onGround=abs(com(3)-rprm(70)/2)<0.003;\n' ...
    '      moved=(com-rcom0).''*rtravel>=rprm(70)*rprm(71);\n' ...
    '      if flat && slow && onGround && moved\n' ...
    '        if rflat<0, rflat=clk; end\n' ...
    '        if clk-rflat>=rprm(69)\n' ...
    '          rs=rs+1; rp=0;\n' ...
    '          if rs>nroute, rp=4; end\n' ...
    '        end\n' ...
    '      else\n' ...
    '        rflat=-1;\n' ...
    '      end\n' ...
    '    end\n' ...
    '    if rp>=1 && rp<=3 && (clk-rstart>rprm(66) || ra>125*pi/180)\n' ...
    '      rp=5; rfault=2;\n' ...
    '    end\n' ...
    '  end\n' ...
    '  tau=[0;0;0];\n' ...
    '  if rp==1, tau(rw)=rg*wDrive; end\n' ...
    '  if rp==2, tau(rw)=-rg*wBleed; end\n' ...
    '  tau=min(max(tau,-peak),peak);\n' ...
    '  for j=1:3\n' ...
    '    %% The 2 ms torque hold can add ~20 rad/s after this chart sees the\n' ...
    '    %% speed. Use an early guard on route mode only.\n' ...
    '    if abs(w(j))>=wmax-rprm(72) && tau(j)*w(j)>0, tau(j)=0; end\n' ...
    '  end\n' ...
    '  routeState=[rs-1;rp;rfault];\n' ...
    '  return\n' ...
    'elseif mode==6 || mode==7 || mode==8\n' ...
    '  %% Edge balance -> vertex. Tips SIDEWAYS about world X, not about the\n' ...
    '  %% contact edge: at edge balance the vertical body direction is the FACE\n' ...
    '  %% diagonal (-1,0,1)/sqrt2 and the contact is a line along world Y, so\n' ...
    '  %% reaching a body-vertical vertex means rotating 35.26 deg about a\n' ...
    '  %% horizontal axis through one END of that edge -- which is world X.\n' ...
    '  %% Wheels X and Z carry it: their world-x components are both +0.7071\n' ...
    '  %% and their world-z components cancel when driven with the same sign,\n' ...
    '  %% so the pair produces a pure world-X torque with no cross-coupling.\n' ...
    '  %% Threshold 0.5445 = m*g*side/2 against a net sqrt(2)*tau per wheel.\n' ...
    '  %% The vertical body diagonal is (-1,1,1)/sqrt3, NOT the (1,1,1)/sqrt3\n' ...
    '  %% the vertex mode uses. The jump pivots on the body corner\n' ...
    '  %% (s/2,-s/2,-s/2), so COM-minus-pivot in body coordinates is\n' ...
    '  %% (-1,1,1)/sqrt3 and that is the diagonal the rotation brings upright.\n' ...
    '  %% Using the wrong one is not a small error: the balance law would read a\n' ...
    '  %% large fictitious tilt at the CORRECT vertex and drive the cube off it.\n' ...
    '  %% Mode 8 (experimental, flat -> vertex in one motion) uprights the\n' ...
    '  %% (1,1,1)/sqrt3 diagonal, the same one mode 3 uses. Modes 6 and 7 pivot\n' ...
    '  %% on a different corner and upright (-1,1,1)/sqrt3 instead.\n' ...
    '  if mode==8\n' ...
    '    n=[0.5773502691896258;0.5773502691896258;0.5773502691896258];\n' ...
    '  else\n' ...
    '    n=[-0.5773502691896258;0.5773502691896258;0.5773502691896258];\n' ...
    '  end\n' ...
    '  u=reshape(R,3,3)*n;\n' ...
    '  thx=-u(2); thy=u(1);\n' ...
    '  if mode==7 && phase<3\n' ...
    '    %% FULL CHAIN, edge stage: Stage B''s proven flat->edge sequence is\n' ...
    '    %% reused verbatim (spin up on Wheel Y below the 0.5445 threshold,\n' ...
    '    %% brake past it, capture with the edge PD).\n' ...
    '    th=thE;\n' ...
    '    if phase==0 && abs(w(2))>=spinW, phase=1; end\n' ...
    '    if phase==1 && (th>=capDeg*pi/180 || w(2)>=0), phase=2; tHand=clk; end\n' ...
    '    %% Hand over to the vertex law once the EDGE IS SETTLED, not after a\n' ...
    '    %% fixed time. The vertex law commands the correct direction from the\n' ...
    '    %% edge attitude (that is exactly why the second hop works), so there\n' ...
    '    %% is no separate climb phase to schedule -- but it must not take over\n' ...
    '    %% while the cube is still rocking on its edge.\n' ...
    '    if phase==2 && abs(th)<2*pi/180 && abs(omega(2))<0.5, phase=3; end\n' ...
    '    if phase==0\n' ...
    '      tau=[0; spinT; 0];\n' ...
    '    elseif phase==1\n' ...
    '      tau=[0; brakeT; 0];\n' ...
    '    else\n' ...
    '      tq=s*(Kp*th+Kd*omega(2))+Kw*w(2)+KiE*wsc(2)+KiT*ths;\n' ...
    '      if abs(tq)<dzE, tq=0; end\n' ...
    '      tau=[0; tq; 0];\n' ...
    '    end\n' ...
    '  elseif mode==6 && jph<2\n' ...
    '    if jph==0\n' ...
    '      tau=[eT0; 0; eT0];\n' ...
    '      if max(abs(w(1)),abs(w(3)))>=eSpinW\n' ...
    '        jph=1; jw0=w(1);\n' ...
    '      end\n' ...
    '    else\n' ...
    '      tau=[eT1; 0; eT1];\n' ...
    '      if jw0*w(1)<=0\n' ...
    '        jph=2;\n' ...
    '      end\n' ...
    '    end\n' ...
    '  elseif mode==6 && jph==2\n' ...
    '    %% COAST to the vertex before engaging the balance law. Engaging it\n' ...
    '    %% at the rotor zero-cross, mid-climb, is what breaks this manoeuvre:\n' ...
    '    %% at edge balance u = (0,0.5774,0.8165) for this diagonal, so the law\n' ...
    '    %% reads a fictitious 33 deg of tilt and drives at peak torque for the\n' ...
    '    %% whole climb -- spending the rotor budget before the cube arrives.\n' ...
    '    %% Measured: rotors pegged at 1819-1848 rad/s against an 1800 limit, so\n' ...
    '    %% the speed guard zeroed the capture torque exactly when it was needed,\n' ...
    '    %% and a clean arrival (0.071 deg, 2.13 rad/s) still fell.\n' ...
    '    tau=[0;0;0];\n' ...
    '    if u(3)>=0.99, jph=3; jtHand=clk; end\n' ...
    '  else\n' ...
    '    %% The allocation is corrected for ATTITUDE. A was identified at the\n' ...
    '    %% vertex, where the wheel axes lie one way; away from it the axes\n' ...
    '    %% rotate with the body, so using A unchanged commands the torque in\n' ...
    '    %% the wrong direction. Measured on the edge->vertex climb: the tilt\n' ...
    '    %% GREW from 33.08 to 53.83 deg (flat is 46.8) -- the loop drove the\n' ...
    '    %% cube away from the vertex -- with u_z swinging over -0.84..+0.85 and\n' ...
    '    %% the rotors winding to -1857 rad/s while spending 0.181 kg*m^2/s per\n' ...
    '    %% wheel for a manoeuvre needing 0.0713. That is why gains, speed and\n' ...
    '    %% torque were all irrelevant: the direction was wrong, not the size.\n' ...
    '    %%\n' ...
    '    %% Since the wheel->axis map is A(R) = -I^-1 * R * B with B the wheel\n' ...
    '    %% axes in body coordinates, dividing by the identified A(R0) gives\n' ...
    '    %%   A(R) = A * (B * R0'' * R * B),  B = diag(1,-1,1)\n' ...
    '    %% (wheel Y''s pose rotation puts its axis along body -y). At R = R0\n' ...
    '    %% this is exactly A, so the vertex results are unchanged; away from\n' ...
    '    %% the vertex it follows the body.\n' ...
    '    Rm=reshape(R,3,3); R0m=reshape(prm(36:44),3,3);\n' ...
    '    Bs=[1 0 0; 0 -1 0; 0 0 1];\n' ...
    '    Ae=A*(Bs*(R0m''*Rm)*Bs);\n' ...
    '    uc=-KpP*[-u(2);u(1)]-KdP*[omega(1);omega(2)];\n' ...
    '    tau=spP*Ae''*((Ae*Ae''+lamP*lamP*eye(3))\\[uc;-KyawP*omega(3)]);\n' ...
    '    %% Rotor-speed integral, added to the WHEEL commands AFTER the\n' ...
    '    %% allocation. Rotor momentum is a per-wheel quantity and so is the\n' ...
    '    %% wheel command; injecting it in task space instead would smear it\n' ...
    '    %% through the pseudo-inverse and it would stop being per-rotor.\n' ...
    '    tau=tau+KiP*wsc;\n' ...
    '  end\n' ...
    '  %% Capture window gated on the STATE, not on a fixed duration. The\n' ...
    '  %% edge->vertex climb takes longer than any short fixed window, so a\n' ...
    '  %% time-based window expires mid-climb and leaves the law with only the\n' ...
    '  %% 0.06 continuous limit, which cannot arrest even 2.7 rad/s (measured:\n' ...
    '  %% the cube arrives at the vertex at 1.66 deg / 2.69 rad/s and falls).\n' ...
    '  %% Peak authority is held while the tilt or the rate is still large.\n' ...
    '  big=hypot(thx,thy)>capTilt*pi/180 || hypot(omega(1),omega(2))>capRate;\n' ...
    '  %% Mode-aware: mode 3 (plain vertex hold) never sets jph, so a bare\n' ...
    '  %% jph<2 test would leave it on PEAK torque for the whole run instead of\n' ...
    '  %% the 0.06 continuous limit. Mode 5 balances at jph==2, mode 6 at\n' ...
    '  %% jph==3 (after its coast).\n' ...
    '  %% mode 8 has no jump phases at all: it is the balance law from t=0, so\n' ...
    '  %% it is always in the "bal" state.\n' ...
    '  bal = (mode==5 && jph==2) || (mode==6 && jph==3) || ' ...
    '(mode==7 && phase==3) || mode==8;\n' ...
    '  %% mode 7 phases 0-2 are the whole edge half (spin, brake, capture) and\n' ...
    '  %% need peak throughout, exactly as Stage B did; phase 3 is the vertex\n' ...
    '  %% hold and uses the same state gate as the other vertex modes. Folding\n' ...
    '  %% it into `jump` keeps BOTH expressions logical -- a later `jump=1`\n' ...
    '  %% assigned a double into an already-logical variable and the chart\n' ...
    '  %% failed to build with no useful diagnostic.\n' ...
    '  jump = ((mode==5 || mode==6) && jph<2) || (mode==7 && phase<3);\n' ...
    '  if jump || (bal && big), cl=peak; else, cl=limit; end\n' ...
    '  tau=min(max(tau,-cl),cl);\n' ...
    '  for i=1:3\n' ...
    '    if abs(w(i))>=wmax && tau(i)*w(i)>0, tau(i)=0; end\n' ...
    '  end\n' ...
    '  return\n' ...
    'elseif mode==3 || mode==5\n' ...
    '  n=[0.5773502691896258;0.5773502691896258;0.5773502691896258];\n' ...
    '  u=reshape(R,3,3)*n;\n' ...
    '  thx=-u(2); thy=u(1);\n' ...
    '  if mode==5 && jph<2\n' ...
    '    %% Flat -> vertex direct tip-up. Phase 0 stores rotor momentum with a\n' ...
    '    %% torque BELOW the tipping threshold, so the cube stays flat while the\n' ...
    '    %% wheels wind up; phase 1 reverses it and exceeds the threshold, which\n' ...
    '    %% tips the cube about the bottom-corner face diagonal by 54.74 deg and\n' ...
    '    %% brings the body diagonal vertical. Both phases drive Wheels X and Y\n' ...
    '    %% with the SAME sign: wheel Y''s axis is world -y, so opposite signs\n' ...
    '    %% would give a torque about (1,1,0), which cannot reach the vertex\n' ...
    '    %% (measured: the cube launches without rotating).\n' ...
    '    %% The brake ends when the rotors have given back everything they\n' ...
    '    %% stored (sign reversal), NOT at an angle: braking on an angle flew\n' ...
    '    %% the cube over the top in Stage B.\n' ...
    '    if jph==0\n' ...
    '      tau=[pT0; pT0; 0];\n' ...
    '      if max(abs(w(1)),abs(w(2)))>=pSpinW\n' ...
    '        jph=1; jw0=w(1);\n' ...
    '      end\n' ...
    '    else\n' ...
    '      tau=[pT1; pT1; 0];\n' ...
    '      if jw0*w(1)<=0\n' ...
    '        jph=2; jtHand=clk;\n' ...
    '      end\n' ...
    '    end\n' ...
    '  else\n' ...
    '    uc=-KpP*[thx;thy]-KdP*[omega(1);omega(2)];\n' ...
    '    tau=spP*A''*((A*A''+lamP*lamP*eye(3))\\[uc;-KyawP*omega(3)]);\n' ...
    '    tau=tau+KiP*wsc;\n' ...
    '    if pprm(1)~=0, tau=tau+pprm(1)*w; end\n' ...
    '  end\n' ...
    '  if mode==5 && jph<2\n' ...
    '    %% The jump needs peak torque: both phases run far above the 0.06\n' ...
    '    %% continuous limit (0.40 to store, 0.80 to brake), and the threshold\n' ...
    '    %% the brake must exceed is 0.5445. Clamping these to the continuous\n' ...
    '    %% limit would make the manoeuvre impossible, not merely slower.\n' ...
    '    cl=peak;\n' ...
    '  elseif mode==5 && clk-jtHand<boostSec\n' ...
    '    %% Capture window after the handover. The cube arrives at the vertex\n' ...
    '    %% with residual rate, and the measured capture basin for the vertex\n' ...
    '    %% is only ~3.5 deg because I*Kp*theta exceeds the 0.06 continuous\n' ...
    '    %% limit by theta ~ 2 deg. Without the boost the manoeuvre reaches the\n' ...
    '    %% vertex attitude and falls straight through: measured u_z peaked at\n' ...
    '    %% 0.99998 (com_z 0.12965) and ended at 0.577 (flat). Same remedy as\n' ...
    '    %% Stage B, which needed it for the same reason.\n' ...
    '    cl=peak;\n' ...
    '  else\n' ...
    '    cl=limit;\n' ...
    '  end\n' ...
    '  tau=min(max(tau,-cl),cl);\n' ...
    '  %% Rotor-speed guard on all three wheels. Leaving this out is not\n' ...
    '  %% academic: a capture that fails spins a wheel to 5998 rad/s against a\n' ...
    '  %% 1800 limit (measured), because the vertex branch used to return\n' ...
    '  %% before reaching the guard the edge branch uses.\n' ...
    '  for i=1:3\n' ...
    '    if abs(w(i))>=wmax && tau(i)*w(i)>0\n' ...
    '      tau(i)=0;\n' ...
    '    end\n' ...
    '  end\n' ...
    '  return\n' ...
    'end\n' ...
    'tq=min(max(tq,-lim),lim);\n' ...
    '%% YAW damping. Measured: every attempt to dump the rotor on the edge dies\n' ...
    '%% of yaw, not of pitch -- over 90 s the surviving config accumulates -0.3\n' ...
    '%% deg of world-Z rotation while every failing one accumulates 44 to 53\n' ...
    '%% deg (exp_edgemode). The edge law had NO yaw feedback at all; only the\n' ...
    '%% vertex law has -KyawP*omega(3).\n' ...
    '%%\n' ...
    '%% At the edge attitude R = RotY(45 deg), the axis of wheel X is world\n' ...
    '%% (0.707, 0, -0.707) and that of wheel Z is (0.707, 0, 0.707): their\n' ...
    '%% world-Z components are OPPOSITE. Driving them with OPPOSITE signs\n' ...
    '%% therefore cancels the world-X part and leaves a pure world-Z torque --\n' ...
    '%% the mirror of the edge->vertex hop, which drives the same two wheels\n' ...
    '%% with the SAME sign for a pure world-X torque. Wheel Y keeps the pitch.\n' ...
    '%% yawRef is the CALLBACK. Holding the yaw rate at exactly zero makes the\n' ...
    '%% X/Z pair carry the whole friction-injected yaw momentum, and a persistent\n' ...
    '%% torque integrates, so their speed grows without bound (measured 0.157\n' ...
    '%% rad/s per second, ~3 h to the limit). Tracking a small NON-ZERO rate\n' ...
    '%% instead lets the pair unwind into the cube, and because friction opposes\n' ...
    '%% that rotation it dissipates the momentum -- the only yaw sink there is.\n' ...
    '%% That is the yaw analogue of leaning to dump pitch momentum into gravity.\n' ...
    '%% It cannot be done with no rotation at all: the two are the same quantity.\n' ...
    '%% yawRef = 0 reproduces the shipped behaviour exactly.\n' ...
    'qy=KyawE*(omega(3)-yawRef);\n' ...
    '%% Never drive a rotor further past its speed limit; braking is allowed.\n' ...
    '%% Applied to all three wheels now that X and Z carry the yaw term.\n' ...
    'tau=min(max([qy;tq;-qy],-lim),lim);\n' ...
    'for i=1:3\n' ...
    '  if abs(w(i))>=wmax && tau(i)*w(i)>0, tau(i)=0; end\n' ...
    'end\n' ...
    'end\n']);
end

function text = localVector(v)
text = sprintf('[%.16g %.16g %.16g]',v(1),v(2),v(3));
end
